### ISSUE TITLE
missing /demo/sample/*.*?

### ISSUE THREAD

**Issue by ourladyofagi** [johannakarras/DreamPose#1]

**Comment by ourladyofagi** [comment]
It appears that I am simply ignorant of the syntax and that the /demo/ folders are not meant to be included but are meant to be supplied by the user, though I am not sure what the formats or contents are. Apologies for the confusion.

**Comment by ourladyofagi** [comment]
I'm just going to update this like a blog in case any other unqualified idiot like me come stumbling along. 

Anyways, in the init__py__ on my install, I needed to add
from .transformer_2d import BasicTransformerBlock
in order to get it to initiate some sort of download, which it is doing now

**Comment by ourladyofagi** [comment]
To be determined whether downloading the UBC Fashion Dataset will kickstart this into action, but at the very least, more things are being downloaded. Link: https://vision.cs.ubc.ca/datasets/fashion/ (down at the bottom)

**Comment by ourladyofagi** [comment]
nah
dunno where the poses in test.py are meant to be coming from
it's quite possible i'm simply too stupid to understand anything about this
i wish you all the best of luck
here's a SD image of a qt 
thank you for coming to my tedtalk
![OurLadyofAGI_1990s_Mamiya_RZ67_profile_view_shot_Kodak_Porta_16_2aad4b0f-6d6d-42c7-8e9f-95af18d189f5_bottom_right](https://user-images.githubusercontent.com/126371399/231652542-e0fb799b-e57c-4a71-87b3-d9e4558dbbcf.jpg)

**Comment by ourladyofagi** [comment]
... instead, my contribution to the project will be telling you that the link on your github is broken:
https://https//grail.cs.washington.edu/projects/dreampose/

![OurLadyofAGI_1980s_Hasselblad_500cm_glamour_shot_Cinestill_50_f_02c8564f-8ada-4702-8245-44f67cd8dfc6_bottom_right](https://user-images.githubusercontent.com/126371399/231656805-4c3fde86-0456-4367-b84a-6c218d2262fb.jpg)

**Comment by johannakarras** [comment]
Thank you for letting me know! I have uploaded the demo/sample folder and updated the README with instructions how to the download the checkpoints and poses.
