### ISSUE TITLE
Not working for custom input images provided

### ISSUE THREAD

**Issue by Parthkh28** [johannakarras/DreamPose#10]
The model doesn't generate the expected keyframes for the custom input image. While running it, it gives the output on the already provided image.
every time getting this image
![pred_#50](https://user-images.githubusercontent.com/80260929/232326821-ff200eca-5020-4dd2-a7a9-b0b77b734233.png)

**Comment by kunalgoyal9** [comment]
Same Issue I faced today.

**Comment by johannakarras** [comment]
The model needs to be subject-specific finetuned (see instructions for "Finetune a Sample" in the README). The provided custom-chkpts are for the particular test image inside demo/sample from the UBC Fashion dataset.

**Comment by Parthkh28** [comment]
So in the demo/sample/train folder we need to provide input image and its densepose by replacing it with it the already present files frames_50.png and frame_50_densepose.npy

**Comment by johannakarras** [comment]
Yes, then run the subject-specific finetuning for UNet and VAE.
