### ISSUE TITLE
hair style is flickering

### ISSUE THREAD

**Issue by weizmann** [johannakarras/DreamPose#12]
Thanks for the wonderful work.

But I found the hair style is not well controlled(flickering when frames changes), can you give me some advise to get a stable hair style?

Here is my result after running the demo
https://drive.google.com/file/d/1gX-bYCjozDGeNCxGCEtFqwxZI2bvIeC4/view?usp=sharing

**Comment by johannakarras** [comment]
We observe minor flickering to be a common limitation of the method. You can potentially improve flickering by training the decoder for additional epochs or increasing the data augmentation during subject-specific finetuning stage.

**Comment by zhangtao22** [comment]
what does this decoder specifically refer to?
> We observe minor flickering to be a common limitation of the method. You can potentially improve flickering by training the decoder for additional epochs or increasing the data augmentation during subject-specific finetuning stage.
