### ISSUE TITLE
How to generate densepose.npy file? which densepose model can i use?

### ISSUE THREAD

**Issue by samggggflynn** [johannakarras/DreamPose#14]
Thank you for your great work !
i have noticed that finetune needs both train images and densepose.npy files.
So could you please **_upload preprocess code for generating densepose.npy files_** and training on my own images.
hope to see a readme step about finetune with more details.

**Comment by samggggflynn** [comment]
> Thank you for your great work ! i have noticed that finetune needs both train images and densepose.npy files. So could you please **_upload preprocess code for generating densepose.npy files_** and training on my own images. hope to see a readme step about finetune with more details.

ps. 
also met an problem in File "finetune-unet.py", line 352, in main
    inputs = clip_processor(images=list(batch['frame_i'].to(latents.device)), return_tensors="pt"). raise ValueError(
ValueError: The image to be converted to a PIL image contains values outside the range [0, 1], got [-1.0, 1.0] which cannot be converted to uint8.

**Comment by johannakarras** [comment]
The densepose.npy files are the UV coordinates extracted from DensePose output at keys 'pred_densepose'. I will upload a script to process and format the raw DensePose output soon.

**Comment by weizmann** [comment]
I got the same error when fine-tuning, any updates for the script and instructions?  @johannakarras

**Comment by weizmann** [comment]
update: I have used the utils/densepose.py to process the instance pngs, but encountered the same error

![image](https://user-images.githubusercontent.com/2306111/233611078-8687b83f-5fc5-4a12-9816-832294d10e34.png)

**Comment by weizmann** [comment]
some kindly recommend: 
as fine-tuning is crucial for getting a better video result, can you give us a detailed instruction/end-to-end example on how to fine-tuning? ☺️
