### ISSUE TITLE
The implementation of adapter

### ISSUE THREAD

**Issue by Wangt-CN** [johannakarras/DreamPose#15]
Thanks a lot for this fantastic work.
After reading the code, I find that you treat the (h*w) (i.e., 40 * 32) as the "channel" and use a linear layer to transfer it to 768.
I wonder why use this kind of implementation rather than use 4 as the "channel"?

**Comment by johannakarras** [comment]
Thank you! The adapter not only jointly models VAE and CLIP embeddings, but also reshapes them to match the shape of the original CLIP text embeddings for the denoising UNet.
