### ISSUE TITLE
files and classes missing error.

### ISSUE THREAD

**Issue by samggggflynn** [johannakarras/DreamPose#17]
hi, there.
While finetune the vae decoder,
I have come across an error that seems to be due to missing files and related classes in code.
> File "finetune-vae.py", line 37, in <module>
    from datasets.train_vae_dataset import DreamBoothDataset
ModuleNotFoundError: No module named 'datasets.train_vae_dataset'

>   File "finetune-vae.py", line 38, in <module>
    from datasets.prompt_dataset import PromptDataset
ModuleNotFoundError: No module named 'datasets.prompt_dataset'

**Comment by samggggflynn** [comment]
fixed

**Comment by ping-Huang** [comment]
@samggggflynn 
I have the same error.
How to fix the ModuleNotFoundError: No module named 'datasets.prompt_dataset'?

**Comment by johannakarras** [comment]
Thank you for pointing these out. They should be fixed in the latest version of finetune-vae.py.
