### ISSUE TITLE
Environment issue: cannot import name 'BasicTransformerBlock' from 'diffusers.models'

### ISSUE THREAD

**Issue by YuanZi1501040205** [johannakarras/DreamPose#21]
I download fresh repo and configured my environment with the following cmds:

git clone https://github.com/johannakarras/DreamPose.git
cd DreamPose/
pip install einopscd
pip install torchvision
pip install transformers

Tried the demo:
python test.py --epoch 499 --folder demo/custom-chkpts --pose_folder demo/sample/poses  --key_frame_path demo/sample/key_frame.png --s1 8 --s2 3 --n_steps 100 --output_dir demo/sample/results --custom_vae demo/custom-chkpts/vae_1499.pth

 got the following errors:
ImportError: cannot import name 'BasicTransformerBlock' from 'diffusers.models' (/home/yzi/miniconda3/envs/diffuser/lib/python3.11/site-packages/diffusers/models/__init__.py)

I checked environment list as following, can anyone help me identify the issue of environment configuration?
# packages in environment at /home/yzi/miniconda3/envs/diffuser:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
accelerate                0.18.0                   pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
cmake                     3.26.3                   pypi_0    pypi
diffusers                 0.15.1                   pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
huggingface-hub           0.13.4                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.5.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
lit                       16.0.1                   pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1                      pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.1                     pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.0.1          py311h06a4308_0  
psutil                    5.9.5                    pypi_0    pypi
python                    3.11.2               h7a1cb2a_0  
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
regex                     2023.3.23                pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
setuptools                66.0.0          py311h06a4308_0  
sqlite                    3.41.2               h5eee18b_0  
sympy                     1.11.1                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.3                   pypi_0    pypi
torch                     2.0.0                    pypi_0    pypi
torchvision               0.15.1                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.28.1                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.15                  pypi_0    pypi
wheel                     0.38.4          py311h06a4308_0  
xz                        5.2.10               h5eee18b_1  
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Comment by h4rk8s** [comment]
vim models/unet_dual_encoder.py

updated: from diffusers.models.attention import BasicTransformerBlock

**Comment by johannakarras** [comment]
Hi, thank you for pointing this out! BasicTransformerBlock is actually an unnecessary import. I have fixed this in the latest version of models/unet_dual_encoder.py.
