### ISSUE TITLE
image resize error when fine-tuning UNet

### ISSUE THREAD

**Issue by weizmann** [johannakarras/DreamPose#23]
I got an error when fine-tuning, any updates for the script and instructions?  @johannakarras 
thanks a lot

_Originally posted by @weizmann in https://github.com/johannakarras/DreamPose/issues/14#issuecomment-1517602279_

**Comment by weizmann** [comment]
update: I have used the utils/densepose.py to process the instance pngs

the error stack is pasted below

![image](https://user-images.githubusercontent.com/2306111/233611078-8687b83f-5fc5-4a12-9816-832294d10e34.png)

**Comment by weizmann** [comment]
some kindly recommends: @johannakarras 
as fine-tuning is crucial for getting a better video result, can you give us a detailed instruction/end-to-end example on how to fine-tune? ☺️

**Comment by johannakarras** [comment]
I think this issue stems from the transforms.Normalize function. I am able to solve it by removing all "transforms.Normalize([0.5], [0.5])" in the dataset scripts. Please try downloading the latest dataset files and let me know if the issue is not resolved.

**Comment by weizmann** [comment]
I have used 10 images for the UNet finetune, but I got the cuda out of memory error

![image](https://user-images.githubusercontent.com/2306111/233816289-d65cf900-a228-45bc-ad9f-0cabfda57e5d.png)
