### ISSUE TITLE
No datasets modules

### ISSUE THREAD

**Issue by david-svitov** [johannakarras/DreamPose#24]
I faced the issue from:
https://github.com/johannakarras/DreamPose/issues/17

And it is still here: no `DreamBoothDataset` and `PromptDataset` in the code

**Comment by david-svitov** [comment]
Looks like I fixed it using `PromptDataset` from here https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py
And renaming `train_vae_dataset.DreamPoseDataset` into `DreamBoothDataset`

**Comment by johannakarras** [comment]
Thanks for the note! Actually, PromptDataset is not used in the code and is left over from the original diffusers training script. I have removed this part and pushed the new version.
