### ISSUE TITLE
where is this Deep_Fashion_Dataset/img_highres and what does ../UBC_Fashion_Dataset/train-frames/*/*png' refer to?

### ISSUE THREAD

**Issue by zhangtao22** [johannakarras/DreamPose#29]
Excuse me，after reviewing the code， I found 
[path for path in glob.glob('../Deep_Fashion_Dataset/img_highres/*/*/*/*.jpg') if os.path.exists(path.replace('.jpg', '_densepose.npy'))]).
where is this dataset?I browsed deep fasion and found that they have several datasets.What is this one?
In addition, what does ../UBC_Fashion_Dataset/train-frames/*/*png' refer to? do you extract frames from UBC_Fashion_Dataset?If that, how did you extract,24 frames every second?

**Comment by johannakarras** [comment]
Hi, this is the Deep Fashion in-shop clothing retrieval dataset. The released checkpoint is only trained on UBC Fashion Videos, but training on Deep Fashion is also an option.

'../UBC_Fashion_Dataset/train-frames/*/*png' refers to the preprocessed training dataset containing every _frame_x.png_ from the UBC Fashion train dataset videos, along withe a corresponding _frame_x_densepose.npy_ densepose file. Frames are extracted via cv2 VidCapture function.
