### ISSUE TITLE
Would you like to share your processed training dataset?

### ISSUE THREAD

**Issue by harlanhong** [johannakarras/DreamPose#3]
Hi, thank you for your impressive work. Could you share the training dataset (including the pose file)?   I want to train it from scratch to make me better understand this code.

**Comment by harlanhong** [comment]
Ok, thanks.

**Comment by harlanhong** [comment]
I examined the pose.npy file and noticed that it contains an array with the dimensions [2, h, w]. Is this a motion field? I've made multiple attempts to acquire this kind of data using DensePose without success. I'm eager to see your processing code.

**Comment by harlanhong** [comment]
I solved that problem. Your motion is the uv matrix:)

**Comment by lirus7** [comment]
Hey!
How do you get the UV matrix from densepose?

**Comment by harlanhong** [comment]
You can modify the code in apply_net.py of DensePose (detectron2)  and get the UV matrix: 
`UV = result["pred_densepose"][0].uv.cpu().numpy()`

**Comment by lirus7** [comment]
Ohhkk. I instead used the dump option in the apply_net.py. It ends up storing the pkl files which contains the densepose-uv.

**Comment by zhangtao22** [comment]
@harlanhong when I got this，
UV = result["pred_densepose"][0].uv.cpu().numpy()，the shape didn't align with the orignal shape. I used frame_50.png to test.Why?
(720, 576, 3)
(2, 653, 192)

**Comment by harlanhong** [comment]
Yes, because authors' densepose.py directly crops the detection bounding box. You can paste the detected result back to the background as following:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/19970321/235037572-90b2495d-11be-4c90-859a-7d7caea13d75.png">
