### ISSUE TITLE
difference in training script and paper

### ISSUE THREAD

**Issue by adwardlee** [johannakarras/DreamPose#34]
Hi @johannakarras,

The training script in README denotes that the base model needs to train 300 epochs with 4 gpus.
`accelerate launch --num_processes=4 train.py --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" --instance_data_dir=../path/to/dataset --output_dir=checkpoints --resolution=512 --train_batch_size=2 --gradient_accumulation_steps=4 --learning_rate=5e-6 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=300 --run_name dreampose --dropout_rate=0.15 --revision "ebb811dd71cdc38a204ecbdd6ac5d580f529fd8c"`

While in the paper, it says the base model only need to train 5 epochs with 2 gpus. Which setting should I use to reproduce your results? Thanks.

**Comment by johannakarras** [comment]
You should use the setting in the paper with 5 epochs and 2 GPU's.

**Comment by zhangtao22** [comment]
@johannakarras so the demo.gif you delivered is trained by 5 epochs?
