### ISSUE TITLE
GPU OOM when multi-gpu training

### ISSUE THREAD

**Issue by flamehaze1115** [johannakarras/DreamPose#40]
Hello, I run the train.py with one 3090 GPU with 24G memory, it works well.
However, when I run multi-gpu training with two GPUs, I met OOM problem.
Like,
> RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 23.70 GiB total capacity; 16.76 GiB already allocated; 2.44 MiB free; 16.9
4 GiB reserved in total by PyTorch) 
If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYT
ORCH_CUDA_ALLOC_CONF

It seems that there is enough memory to allocate, but it still met the problem.
I tried to set `os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:32"`, but it doesn't work.

For single GPU, with train_batch_size=2, gradient_accumulation_steps=4, the training works well.
However, for two GPUs, with train_batch_size=1, gradient_accumulation_steps=1, the training will met the OOM problem.

**Comment by NguyenTriTrinh** [comment]
Hi, @flamehaze1115! I tried running train.py or finetune-unet.py with a single 24 GB 3090 GPU using the default args, but it also resulted in an OOM problem. Could you please provide me with some tips?

**Comment by flamehaze1115** [comment]
> Hi, @flamehaze1115! I tried running train.py or finetune-unet.py with a single 24 GB 3090 GPU using the default args, but it also resulted in an OOM problem. Could you please provide me with some tips?

Hello. I found the OOM problem I met is due to some issues of GPU itself. Rebooting the system solve my problem. Hope it can help you.

**Comment by emreaniloguz** [comment]
> Hi, @flamehaze1115! I tried running train.py or finetune-unet.py with a single 24 GB 3090 GPU using the default args, but it also resulted in an OOM problem. Could you please provide me with some tips?

Same here #47 .
