### ISSUE TITLE
finetuning-unet causes error

### ISSUE THREAD

**Issue by jmahajan117** [johannakarras/DreamPose#45]
Hello, I was trying to run the finetune-unet.py file and I'm getting this error.

`OSError: Consistency check failed: file should be of size 1215981833 but has size 492265879 (model.safetensors).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.`

I have added the arguments to pipeline but I'm still getting this error. Is there any fixes for this?

**Comment by jmahajan117** [comment]
Follow-up: for anyone that got it to work or even better if @johannakarras could answer what version of huggingface_hub & diffuser was used.

**Comment by ravitejavemuri** [comment]
@jmahajan117 
I was facing this issue in train.py tried the below approach - I could get rid of that error for now, not sure if it'd affect the outputs.
it'd be for sure better if @johannakarras could clarify.

using diffusers 0.17.1
in finetune-unet.py
In line 
38 from pipelines.dual_encoder_pipeline import StableDiffusionImg2ImgPipeline

to 
from diffusers import StableDiffusionImg2ImgPipeline


in line 433 load it like this : https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/img2img#diffusers.StableDiffusionImg2ImgPipeline.__call__.example

**Comment by jmahajan117** [comment]
@ravitejavemuri I'm still getting that error. Could you share how you called the model exactly?

**Comment by ravitejavemuri** [comment]
@jmahajan117 
pipeline = StableDiffusionImg2ImgPipeline.from_pretrained(
            args.pretrained_model_name_or_path)

**Comment by ravitejavemuri** [comment]
@jmahajan117 just finished checking, it saves the model but does not work.

pipelines/duel_encoder_pipeline.py does something specific than loading it from diffusers.

exploring it!

**Comment by nikkozzblu** [comment]
Working fine for me on revision "main" (same as no revision)
However you also need to revisit the code because the revision hash is hard-coded in various parts

**Comment by jmahajan117** [comment]
Thanks, @nikkozzblu. I was able to fix this by removing the revision argument everywhere!
