### ISSUE TITLE
CUDA out of memory error while Fine-Tuning the DreamPose

### ISSUE THREAD

**Issue by emreaniloguz** [johannakarras/DreamPose#47]
Hi,

While I try to fine-tune the pre-trained DreamPose model with the demo data given with the project, I'm facing OOM error. I tried to play with batch sizes, and resolution but the result is the same.

- I have 2x3090 in my system.
- I can run the demo.py with 16~17 GB vRAM
- I have used ```accelerate launch finetune-unet.py --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" --instance_data_dir=demo/sample/train --output_dir=demo/custom-chkpts --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=1e-5 --num_train_epochs=500 --dropout_rate=0.0 --custom_chkpt=checkpoints/unet_epoch_20.pth --revision "ebb811dd71cdc38a204ecbdd6ac5d580f529fd8c" ``` command and changed the resolution to the powers of 2, to 4 but didn't work either.
- I have tried to do distributed training with the config of accelerate but it didn't work either.
- I have watched the GPU usage with ```watch nvidia-smi```, and it seems that without using all of the GPU, the code generates an error.

The error is:

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 800.00 MiB (GPU 0; 23.70 GiB total capacity; 16.55 GiB already allocated; 407.56 MiB free; 17.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Steps:   0%|                                                                   | 0/5 [00:01<?, ?it/s]
 WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 18804 closing signal SIGTERM> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 18803) of binary: ****/anaconda3/envs/****

**Comment by emreaniloguz** [comment]
Just find out there is an argument "use_8bit_adam" in the finetune-unet.py while debugging. Adding this parameter solved the problem.

**Comment by chenbolin-master** [comment]
"use_8bit_adam" in the finetune-unet.py while debugging   , how much memory it need ?
@emreaniloguz

**Comment by emreaniloguz** [comment]
> "use_8bit_adam" in the finetune-unet.py while debugging , how much memory it need ?
> @emreaniloguz

In the comments, it says it should be activated for 16 GB GPUs but it uses ~20 GB
