### ISSUE TITLE
Implementation Question

### ISSUE THREAD

**Issue by ourladyofagi** [johannakarras/DreamPose#5]
What would be the correct methodology for getting this dress animated? 

![key_frame](https://user-images.githubusercontent.com/126371399/231794467-d20a1a54-0961-4a55-a311-ce5cd21e1781.png)

as an input frame is currently producing:

![pred_#50](https://user-images.githubusercontent.com/126371399/231795308-1058423e-6584-43eb-bc19-faadcbde9747.png)

Is it that every dress must be fine-tuned? Some combination of guidance / strength / steps that I haven't discovered yet? Some deep misunderstanding I've not listed here?

Thank you <3

**Comment by ourladyofagi** [comment]
Just read the paper. (Finally.) Realized my fundamental misunderstanding. Cheaper and quicker to hire a model than run 2xA100 to fine every iteration, so this is outside my utility-scope. Good luck!

**Comment by kunalgoyal9** [comment]
@ourladyofagi How did you fixed this issue? Every time it is generating for the same model. Thanks
<img width="409" alt="image" src="https://user-images.githubusercontent.com/21281457/232327156-f8304555-b278-4c88-a545-bb434bd50e4a.png">

**Comment by ourladyofagi** [comment]
> @ourladyofagi How did you fixed this issue? Every time it is generating for the same model. Thanks 
I radically misunderstood what this does. I think I was projecting my wishes for what it does onto what it does. It doesn't do that. I'm trying to figure out the utility of how having a photo of a model in a specific dress can be transmuted to a bad short video of a model in a that dress with 30 minutes of A100 training, but I cannot for the life of me come up for a usecase with any bearing on any scenario in any universe.
