### ISSUE TITLE
Paper typo: wrong equation for classifier-free guidance.

### ISSUE THREAD

**Issue by pkhungurn** [johannakarras/DreamPose#6]
Congratulation on your and your team's excellent work. I am very interested in it and have been keenly studying your paper.

I found that Equation (2) on page 4 for classifier-free guidance might be wrong.

![image](https://user-images.githubusercontent.com/25254747/231926830-f544314d-de6e-4945-92fd-b86cfa7a9096.png)

The above image is captured from the PDF I downloaded from arXiv on 2023/4/14.

IMHO, I think it should be 

$$\epsilon_\theta = \epsilon_{\theta}(\tilde{z}_t, t, \emptyset) + s\big( \epsilon_{\theta}(\tilde{z}_t, t, c) - \epsilon_{\theta}(\tilde{z}_t, t, \emptyset) \big) $$

You seem to use the above equation implicitly in Equation (4) on page 6, albeit with the symbol $e$ rather than $\epsilon_\theta$.

**Comment by johannakarras** [comment]
Thank you! This will be fixed in the latest version.
